J.Web/Areas/Admin/Controllers/UserController.cs
using System.Linq;
using System.Web.Mvc;
using J.DB;
using Newtonsoft.Json;
using J.Web.App_Code;
using J.Util;

namespace J.Web.Areas.Admin.Controllers
{
    public class UserController : BaseController
	{
		/// <summary>
		///     User List
		/// </summary>
		/// <returns></returns>
		public ActionResult Index()
		{
			using (var db = new DBEntities())
			{
				var list = from u in db.users
					select
						new
						{
							u.GUID,
							u.ShowName,
							u.LoginName,
							u.Email,
							u.CreateDateTime,
							LastLogin = u.user_loginlogs.Count >= 0 ? u.user_loginlogs.Max(p => p.LoginDateTime) : u.CreateDateTime,
							LoginCount = u.user_loginlogs.Count
						};

                ViewBag.listJson = BasicTools.Object2JavaScriptJsonString("listJson", new { items = list });
			}
			return View();
		}

		public ActionResult LoginLogs(string userID)
		{
			using (var db = new DBEntities())
			{
				var user = (from u in db.users
						   where u.GUID == userID.ToLower()
						   select
							   new
							   {
								   u.GUID,
								   u.ShowName,
								   u.LoginName,
								   u.Email,
								   u.CreateDateTime,
								   LoginCount = u.user_loginlogs.Count
							   }).FirstOrDefault();

				var list = from l in db.user_loginlogs
						   where l.userID == userID.ToLower()
						   orderby l.LoginDateTime descending 
						   select
							   new
							   {
								   l.LoginDateTime
							   };

                ViewBag.userJson = BasicTools.Object2JavaScriptJsonString("userJson", user);
                ViewBag.listJson = BasicTools.Object2JavaScriptJsonString("listJson", new { items = list });
			}

			return View();
		}
	}
}

J.Web/Controllers/SingleController.cs
using J.DB;
using J.Util;
using J.Web.App_Code;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace J.Web.Controllers
{
    public class SingleController : BaseController
    {
        //
        // GET: /Single/
        public ActionResult Index(int PageSize = 25, int PageIndex = 1, int? SingleIntNumber_min = null, int? SingleIntNumber_max = null, int? SingleIntEnum = null,
            decimal? SingleMoney_min = null, decimal? SingleMoney_max = null, DateTime? SingleDatetime_min = null, DateTime? SingleDatetime_max = null,
            string SingleVarchar = null, bool? SingleBit = null)
        {
            using (DBEntities db = new DBEntities())
            {
                var query = from s in db.singles
                            where (SingleIntNumber_min == null || SingleIntNumber_min.Value <= s.SingleIntNumber) &&
                            (SingleIntNumber_max == null || SingleIntNumber_max.Value >= s.SingleIntNumber) &&
                            (SingleIntEnum == null || (J.DB.Enum.single.SingleIntEnum)SingleIntEnum.Value == s.SingleIntEnum) &&
                            (SingleMoney_min == null || SingleMoney_min.Value <= s.SingleMoney) &&
                            (SingleMoney_max == null || SingleMoney_max.Value >= s.SingleMoney) &&
                            (SingleDatetime_min == null || SingleDatetime_min.Value <= s.SingleDatetime) &&
                            (SingleDatetime_max == null || SingleDatetime_max.Value >= s.SingleDatetime) &&
                            (SingleVarchar == null || s.SingleVarchar.Contains(SingleVarchar)) &&
                            (SingleBit == null || SingleBit.Value == s.SingleBit)
                            orderby s.SingleDatetime descending
                            select s;

                int RecordCount = query.Count();

                if (RecordCount <= (PageIndex - 1) * PageSize)
                    PageIndex = 1;

                var data = query.Skip((PageIndex - 1) * PageSize).Take(PageSize).ToList();

                if (Request.IsAjaxRequest())
                {
                    return this.Content(new ReturnObject()
                    {
                        status = data == null ? ReturnObject.EReturnStatus.error : ReturnObject.EReturnStatus.success,
                        message = data == null ? "您要获取的数据不存在！" : "获取数据成功",
                        data = new { items = data, RecordCount = RecordCount, PageSize = PageSize, PageIndex = PageIndex }
                    }.ToString());
                }
                else
                {
                    ViewBag.dataJson = BasicTools.Object2JavaScriptJsonString("dataJson", new { items = data, RecordCount = RecordCount, PageSize = PageSize, PageIndex = PageIndex });
                    return View();
                }
            }
        }

        public ActionResult Detail(string guid)
        {
            using (DBEntities db = new DBEntities())
            {
                var item = db.singles.FirstOrDefault(p => p.GUID == guid.ToLower());

                return this.Content(new ReturnObject()
                {
                    status = item == null ? ReturnObject.EReturnStatus.error : ReturnObject.EReturnStatus.success,
                    message = item == null ? "您要获取的数据不存在！" : "获取数据成功",
                    data = item
                }.ToString());
            }
        }

        [HttpPost]
        public ActionResult Add(string jsonobj)
        {
            jsonobj = HttpUtility.UrlDecode(Encoding.UTF8.GetString(Convert.FromBase64String(jsonobj)));
            using (DBEntities db = new DBEntities())
            {
                var item = JsonConvert.DeserializeObject<single>(jsonobj);

                item.GUID = BasicTools.NewGuid();

                db.singles.Add(item);
                db.SaveChanges();

                return this.Content(new ReturnObject()
                {
                    status = ReturnObject.EReturnStatus.success,
                    message = "添加数据成功！",
                    data = item
                }.ToString());
            }
        }

        [HttpPost]
        public ActionResult Edit(string jsonobj)
        {
            using (DBEntities db = new DBEntities())
            {
                var item = JsonConvert.DeserializeObject<single>(jsonobj);

                db.singles.Attach(item);
                db.Entry(item).State = System.Data.Entity.EntityState.Modified;

                db.SaveChanges();

                return this.Content(new ReturnObject()
                {
                    status = ReturnObject.EReturnStatus.success,
                    message = "添加数据成功！",
                    data = item
                }.ToString());
            }
        }

        [HttpPost]
        public ActionResult Delete(string guid)
        {
            using (DBEntities db = new DBEntities())
            {
                var item = db.singles.FirstOrDefault(p => p.GUID == guid.ToLower());

                db.singles.Remove(item);
                db.SaveChanges();

                return this.Content(new ReturnObject()
                {
                    status = ReturnObject.EReturnStatus.success,
                    message = "删除数据成功！"
                }.ToString());
            }
        }
    }
}

J.Web/Views/Single/Index.cshtml
@{
    ViewBag.Title = "Index";
}
@section head{
}
<h2>List</h2>

<table class="table table-bordered condition">
    <tbody>
        <tr>
            <td>SingleIntNumber</td>
            <td>
                <input type="text" id="Condition_SingleIntNumber_min" />
                ~
                <input type="text" id="Condition_SingleIntNumber_max" />
            </td>
            <td>SingleIntEnum</td>
            <td>
                <select id="Condition_SingleIntEnum">
                    <option value="1">One</option>
                    <option value="2">Two</option>
                </select>
            </td>
        </tr>
        <tr>
            <td>SingleMoney</td>
            <td>
                <input type="text" id="Condition_SingleMoney_min" />
                ~
                <input type="text" id="Condition_SingleMoney_max" />
            </td>
            <td>SingleDatetime</td>
            <td>
                <input type="text" id="Condition_SingleDatetime_min" />
                ~
                <input type="text" id="Condition_SingleDatetime_max" />
            </td>
        </tr>
        <tr>
            <td>SingleVarchar</td>
            <td><input type="text" id="Condition_SingleVarchar" /></td>
            <td>SingleBit</td>
            <td>
                <select id="Condition_SingleBit">
                    <option value="All">All</option>
                    <option value="1">true</option>
                    <option value="0">false</option>
                </select>
            </td>
        </tr>
    </tbody>
    <tfoot>
        <tr>
            <td colspan="4" align="center">
                <button type="button" class="btn btn-primary" id="btnSearch">Search</button>
            </td>
        </tr>
    </tfoot>
</table>

<button type="button" class="btn btn-link pull-right" id="btnAddDialog">Add</button>
<div class="table-responsive" id="Data">
    <table id="dataTable" data-template="dataTableScript" class="table table-bordered table-striped table-hover"></table>
</div>
<ul id="dataTablePager" class="pagination">
    <li class="disabled"><a href="#">&laquo;</a></li>
    <li class="active"><a href="#">1 <span class="sr-only">(current)</span></a></li>
    ...
</ul>

@Html.Partial("~/Views/Single/_Add.cshtml")
@Html.Partial("~/Views/Single/_Delete.cshtml")
@Html.Partial("~/Views/Single/_Detail.cshtml")
@Html.Partial("~/Views/Single/_Edit.cshtml")

@section scripts{
    <script id="dataTableScript" type="text/x-mustache">
        <thead>
            <tr>
                <th>SingleIntNumber</th>
                <th>SingleIntEnum</th>
                <th>SingleMoney</th>
                <th>SingleDatetime</th>
                <th>SingleVarchar</th>
                <th>SingleLongVarchar</th>
                <th>SingleBit</th>
                <th width="200px;">Action</th>
            </tr>
        </thead>
        <tbody>
            {{#items}}
            <tr data-guid="{{GUID}}">
                <td style="text-align:right;">{{SingleIntNumber}}</td>
                <td style="text-align:right;">{{SingleIntEnumString}}</td>
                <td style="text-align:right;">{{SingleMoneyString}}</td>
                <td style="text-align:center;">{{SingleDatetimeString}}</td>
                <td><p>{{SingleVarchar}}</p></td>
                <td><pre>SingleLongVarchar</pre></td>
                <td style="text-align:center;">{{{SingleBitString}}}</td>
                <td style="text-align:center;">
                    <button type="button" class="btn btn-link btn-xs" onclick="ShowDetailDialog('{{GUID}}')">Detail</button><br />
                    <button type="button" class="btn btn-link btn-xs" onclick="ShowEditDialog('{{GUID}}')">Edit</button> |
                    <button type="button" class="btn btn-link btn-xs" onclick="ShowDeleteDialog('{{GUID}}')">Delete</button>
                </td>
            </tr>
            {{/items}}
        </tbody>
    </script>

    <script type="text/javascript">
        {
            var Single_Index_url = "@Url.Action("Index", "Single", new { area = "" }, null)";

            @Html.Raw(ViewBag.dataJson)
            var PageSize = 25;
        }

        $(function () {
            $.initTemplate();

            $("#dataTable").data("template_extend", {
                SingleDatetimeString: function () {
                    return this.SingleDatetime.format("yyyy-mm-dd HH:ii:ss");
                },
                SingleIntEnumString: function () {
                    switch (this.SingleIntEnum) {
                        case 1:
                            return "One";
                        case 2:
                            return "Two";
                        default:
                            return "";
                    }
                },
                SingleMoneyString: function () {
                    return Math.round(this.SingleMoney * 100) / 100;
                },
                SingleBitString: function () {
                    if (this.SingleBit == true)
                        return "<i class='fa fa-check'></i>";
                    else
                        return "<i class='fa fa-times'></i>";
                }
            });
            $("#dataTable").render(dataJson);
            FillPager($("#dataTablePager"), dataJson);

            $('#Condition_SingleDatetime_min').datetimepicker({
                format: 'yyyy-mm-dd hh:ii',
                autoclose: true,
                todayBtn: true,
                todayHighlight: true
            });

            $('#Condition_SingleDatetime_max').datetimepicker({
                format: 'yyyy-mm-dd hh:ii',
                autoclose: true,
                todayBtn: true,
                todayHighlight: true
            });

            $("#btnAddDialog").click(function () {
                ShowAddDialog();
            });


        });

        function SearchData(PageIndex) {
            if (!PageIndex)
                PageIndex = 1;

            SingleIntNumber_min = parseInt($("#Condition_SingleIntNumber_min").val())
            SingleIntNumber_max = parseInt($("#Condition_SingleIntNumber_max").val())
            SingleIntEnum = $("#Condition_SingleIntEnum").val();
            SingleMoney_min = parseFloat($("#Condition_SingleMoney_min").val())
            SingleMoney_max = parseFloat($("#Condition_SingleMoney_max").val())
            SingleDatetime_min = new Date($("#Condition_SingleDatetime_min").val())
            SingleDatetime_max = new Date($("#Condition_SingleDatetime_min").val())

            $.ajax({
                type: "get",
                cache: false,
                url: Single_Index_url,
                data: {
                    PageIndex: PageIndex,
                    PageSize: PageSize,
                    SingleIntNumber_min: parseInt($("#Condition_SingleIntNumber_min").val()),
                    SingleIntEnum: $("AddDialog input:radio[name='SingleIntEnum']:checked").val(),
                    SingleMoney: $("#AddDialog_SingleMoney").val(),
                    SingleDatetime: $("#AddDialog_SingleDatetime").val(),
                    SingleVarchar: $("#AddDialog_SingleVarchar").val(),
                    SingleLongVarchar: $("#AddDialog_SingleLongVarchar").val(),
                    SingleBit: $("#AddDialog_SingleLongVarchar").prop("checked")
                },
                success: function (returnstring) {
                    var returnobj = JSON.parse(returnstring);
                    if (returnobj.status > 0) {
                        $("#AddDialog").modal("hide");
                        $("#MessageBox_alert").addClass("alert-success");
                        $("#MessageBox_message").html(returnobj.message);
                    } else {
                        $("#AddDialog_alert_message").html(returnobj.message);
                        $("#AddDialog_alert").removeClass('hidden');
                    }
                },
                error: function (xmlHttpRequest, textStatus, errorThrown) {
                    $("#AddDialog_alert_message").html("网络错误，请重试！");
                    $("#AddDialog_alert").removeClass('hidden');
                },
                complete: function (xmlHttpRequest, textStatus) {
                    $('#AddDialog_Accept').button('reset');
                }
            });
        }

        function FillPager($pager, data) {
            $pager.empty();
            var maxPage = Math.ceil(data.RecordCount / data.PageSize);
            var beginPage = 2, endPage = maxPage - 1;
            if (maxPage > 13) {
                var beforePages = 5, afterPages = 5;
                beforePages = data.PageIndex - beginPage >= 5 ? 5 : data.PageIndex - beginPage;
                afterPages = endPage - data.PageIndex >= 5 ? 5 : endPage - data.PageIndex;
                if (beforePages < 5) {
                    if (endPage - data.PageIndex >= (5 - beforePages) + 5)
                        afterPages += (5 - beforePages);
                    else
                        afterPages = endPage - data.PageIndex;
                }
                if (afterPages < 5) {
                    if (data.PageIndex - beginPage >= (5 - afterPages) + 5)
                        beforePages += (5 - afterPages);
                    else
                        beforePages = data.PageIndex - beginPage;
                }

                beginPage = data.PageIndex - beforePages;
                endPage = data.PageIndex + afterPages;
            }

            if (data.PageIndex == 1) {
                $pager.append('<li class="disabled"><a href="#">&laquo;</a></li>');
                $pager.append('<li class="active"><a href="#">1</a></li>');
            }
            else {
                $pager.append('<li><a href="javascript:SearchData(1)">&laquo;</a></li>');
                $pager.append('<li><a href="javascript:SearchData(1)">1</a></li>');
            }
            if (beginPage > 2)
                $pager.append("...");
            for (var i = beginPage; i <= endPage; i++) {
                if (i != data.PageIndex) {
                    $pager.append('<li><a href="javascript:SearchData(' + i + ')">' + i + '</a></li>');
                }
                else {
                    $pager.append('<li class="active"><a href="#">' + i + '</a></li>');
                }
            }
            if (endPage + 1 < maxPage)
                $pager.append("...");
            if (maxPage == 1)
            {
                $pager.append('<li class="disabled"><a href="#">&raquo;</a></li>');
            }
            else if (data.PageIndex == maxPage) {
                $pager.append('<li class="active"><a href="#">' + maxPage + '</a></li>');
                $pager.append('<li class="disabled"><a href="#">&raquo;</a></li>');
            }
            else {
                $pager.append('<li><a href="javascript:SearchData(' + maxPage + ')">' + maxPage + '</a></li>');
                $pager.append('<li><a href="javascript:SearchData(' + maxPage + ')">&raquo;</a></li>');
            }
        }
    </script>
}

J.Web/Views/Single/_Add.cshtml
@{
    Layout = null;
}

<!-- Add -->
<div class="modal fade" id="AddDialog" tabindex="-1" role="dialog" aria-hidden="true" data-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h2 class="modal-title">添加</h2>
            </div>
            <form id="AddDialog_form" method="post" action="">
                <div class="modal-body">
                    <div class="form-group">
                        <label for="AddDialog_SingleIntNumber" class="control-label">SingleIntNumber</label>
                        <input type="number" class="form-control" id="AddDialog_SingleIntNumber" name="SingleIntNumber" placeholder="Enter SingleIntNumber" />
                    </div>
                    <div class="form-group">
                        <label class="show control-label">SingleIntEnum</label>
                        <div class="radio-inline">
                            <label><input type="radio" name="SingleIntEnum" id="AddDialog_SingleIntEnum_1" value="1" />One</label>
                        </div>
                        <div class="radio-inline">
                            <label><input type="radio" name="SingleIntEnum" id="AddDialog_SingleIntEnum_2" value="2" />Two</label>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="AddDialog_SingleMoney" class="control-label">SingleMoney</label>
                        <input type="number" class="form-control" id="AddDialog_SingleMoney" name="SingleMoney" placeholder="Enter SingleMoney" />
                    </div>
                    <div class="form-group">
                        <label for="AddDialog_SingleDatetime" class="control-label">SingleDatetime</label>
                        <input type="text" class="form-control" id="AddDialog_SingleDatetime" name="SingleDatetime" placeholder="Enter SingleDatetime" readonly />
                    </div>
                    <div class="form-group">
                        <label for="AddDialog_SingleVarchar" class="control-label">SingleVarchar</label>
                        <input type="text" class="form-control" id="AddDialog_SingleVarchar" name="SingleVarchar" placeholder="Enter SingleVarchar" />
                    </div>
                    <div class="form-group">
                        <label for="AddDialog_SingleLongVarchar" class="control-label">SingleLongVarchar</label>
                        <textarea class="form-control" rows="5" id="AddDialog_SingleLongVarchar_textarea" name="SingleLongVarchar"></textarea>
                        <input type="hidden" id="AddDialog_SingleLongVarchar" name="SingleLongVarchar" />
                    </div>
                    <div class="form-group">
                        <label>
                            <input type="checkbox" name="SingleBit" id="AddDialog_SingleBit" checked>
                            Is Right
                        </label>
                    </div>
                    <div class="alert alert-danger alert-dismissable hidden" id="AddDialog_alert">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                        <p id="AddDialog_alert_message"></p>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" id="AddDialog_Accept" class="btn btn-lg btn-warning" data-loading-text="正在添加...">添加</button>
                    <button type="button" id="AddDialog_Cancel" class="btn btn-lg btn-warning" data-dismiss="modal">取消</button>
                </div>
            </form>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<script type="text/javascript">
    {
        var Single_Add_url = "@Url.Action("Add", "Single", new { area = "" }, null)";
    }

    $(function () {
        var initialDate = new Date();
        var startDate = new Date();
        startDate.setDate(initialDate.getDate() - 7);
        var endDate = new Date();
        endDate.setDate(initialDate.getDate() + 7);
        $('#AddDialog_SingleDatetime').datetimepicker({
            format: 'yyyy-mm-dd hh:ii',
            autoclose: true,
            todayBtn: true,
            todayHighlight: true,
            initialDate: initialDate,
            startDate: startDate,
            endDate: endDate
        });

        tinymce.init({
            selector: "textarea#AddDialog_SingleLongVarchar_textarea",
            init_instance_callback: function (editor) {
                editor.on('change', function (e) {
                    $("#AddDialog_SingleLongVarchar").val(editor.getContent());
                });
            }
        });

        $("#AddDialog_form").validate({
            rules: {
                SingleIntNumber: {
                    required: true,
                    number: true,
                    min: -999,
                    max: 999
                },
                SingleIntEnum: {
                    required: true,
                },
                SingleMoney: {
                    required: true,
                    number: true,
                    range: [0, 999]
                },
                SingleDatetime: {
                    required: true,
                    date: true
                },
                SingleVarchar: {
                    maxlength: 300
                },
                SingleLongVarchar: {
                    maxlength: 2000
                }
            },
            messages: {
                SingleBit: {
                    minlength: "至少选择2项"
                }
            },
            submitHandler: function (form) {
                $("#AddDialog_alert_message").html("");
                $("#AddDialog_alert").addClass('hidden');
                $("#AddDialog_Accept").button("loading");

                var poststring = $.base64.encode(escape(JSON.stringify({
                        SingleIntNumber: $("#AddDialog_SingleIntNumber").val(),
                        SingleIntEnum: $("#AddDialog input:radio[name='SingleIntEnum']:checked").val(),
                        SingleMoney: $("#AddDialog_SingleMoney").val(),
                        SingleDatetime: $("#AddDialog_SingleDatetime").val(),
                        SingleVarchar: $("#AddDialog_SingleVarchar").val(),
                        SingleLongVarchar: $("#AddDialog_SingleLongVarchar").val(),
                        SingleBit: $("#AddDialog_SingleBit").prop("checked")
                    })));
                $.ajax({
                    type: "post",
                    cache: false,
                    url: Single_Add_url,
                    data: { "jsonobj": poststring },
                    success: function (returnstring) {
                        var returnobj = JSON.parse(returnstring);
                        if (returnobj.status > 0) {
                            $("#AddDialog").modal("hide");
                            $("#MessageBox_alert").addClass("alert-success");
                            $("#MessageBox_message").html(returnobj.message);
                        } else {
                            $("#AddDialog_alert_message").html(returnobj.message);
                            $("#AddDialog_alert").removeClass('hidden');
                        }
                    },
                    error: function (xmlHttpRequest, textStatus, errorThrown) {
                        $("#AddDialog_alert_message").html("网络错误，请重试！");
                        $("#AddDialog_alert").removeClass('hidden');
                    },
                    complete: function (xmlHttpRequest, textStatus) {
                        $('#AddDialog_Accept').button('reset');
                        SearchData();
                    }
                });
            }
        });

        $("#AddDialog").on("hidden.bs.modal", function (e) {
            $("#AddDialog_SingleIntNumber").val("");
            $("#AddDialog_SingleIntEnum_1").prop("checked", false);
            $("#AddDialog_SingleIntEnum_2").prop("checked", false);
            $("#AddDialog_SingleMoney").val("");
            $("#AddDialog_SingleDatetime").val("");
            $("#AddDialog_SingleVarchar").val("");
            tinymce.get('AddDialog_SingleLongVarchar').setContent("");
            $("#AddDialog_SingleBit").prop("checked", true);

            $("#AddDialog_alert").addClass("hidden");
            $("#AddDialog_alert_message").html("");

            $('#AddDialog_Accept').button('reset');

            $("#AddDialog_form").validate().resetForm();
            $("#AddDialog .has-error").removeClass("has-error");
        });
    });

    function ShowAddDialog() {
        $("#AddDialog").modal("show");
    }
</script>

J.Web/Views/Single/_Delete.cshtml
@{
    Layout = null;
}

<!-- Delete -->
<div class="modal fade" id="DeleteDialog" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h2 class="modal-title">详细</h2>
            </div>
            <form id="DeleteDialog_form">
                <div class="modal-body form-horizontal">
                    <div class="form-group">
                        <label for="DeleteDialog_GUID" class="col-sm-3 control-label">GUID</label>
                        <div class="col-sm-9">
                            <p class="form-control-static" id="DeleteDialog_GUID"></p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="DeleteDialog_SingleIntNumber" class="col-sm-3 control-label">SingleIntNumber</label>
                        <div class="col-sm-9">
                            <p class="form-control-static" id="DeleteDialog_SingleIntNumber"></p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="DeleteDialog_SingleIntEnum" class="col-sm-3 control-label">SingleIntEnum</label>
                        <div class="col-sm-9">
                            <p class="form-control-static" id="DeleteDialog_SingleIntEnum"></p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="DeleteDialog_SingleMoney" class="col-sm-3 control-label">SingleMoney</label>
                        <div class="col-sm-9">
                            <p class="form-control-static" id="DeleteDialog_SingleMoney"></p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="DeleteDialog_SingleDatetime" class="col-sm-3 control-label">SingleDatetime</label>
                        <div class="col-sm-9">
                            <p class="form-control-static" id="DeleteDialog_SingleDatetime"></p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="DeleteDialog_SingleVarchar" class="col-sm-3 control-label">SingleVarchar</label>
                        <div class="col-sm-9">
                            <p class="form-control-static" id="DeleteDialog_SingleVarchar"></p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="DeleteDialog_SingleLongVarchar" class="col-sm-3 control-label">SingleLongVarchar</label>
                        <div class="col-sm-9">
                            <p class="form-control-static" id="DeleteDialog_SingleLongVarchar">

                            </p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="DeleteDialog_SingleBit" class="col-sm-3 control-label">SingleBit</label>
                        <div class="col-sm-9">
                            <p class="form-control-static" id="DeleteDialog_SingleBit">
                                <i class="fa fa-check"></i><i class="fa fa-times"></i>
                            </p>
                        </div>
                    </div>
                    <div class="alert alert-danger alert-dismissable hidden" id="DeleteDialog_alert">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                        <p id="DeleteDialog_alert_message"></p>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" id="DeleteDialog_Close" class="btn btn-lg btn-warning">关闭</button>
                    <button type="button" id="DeleteDialog_Close" class="btn btn-lg btn-warning" data-dismiss="modal">关闭</button>
                </div>
            </form>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<script type="text/javascript">
    {
        var Common_User_Delete_url = "@Url.Action("Delete", "User", new { area = "Common" }, null)";
    }

    $(function () {
    });
</script>