J.Web/Areas/Admin/Controllers/UserController.cs
using System.Linq;
using System.Web.Mvc;
using J.DB;
using Newtonsoft.Json;
using J.Web.App_Code;
using J.Util;

namespace J.Web.Areas.Admin.Controllers
{
    public class UserController : BaseController
	{
		/// <summary>
		///     User List
		/// </summary>
		/// <returns></returns>
		public ActionResult Index()
		{
			using (var db = new DBEntities())
			{
				var list = from u in db.users
					select
						new
						{
							u.GUID,
							u.ShowName,
							u.LoginName,
							u.Email,
							u.CreateDateTime,
							LastLogin = u.user_loginlogs.Count >= 0 ? u.user_loginlogs.Max(p => p.LoginDateTime) : u.CreateDateTime,
							LoginCount = u.user_loginlogs.Count
						};

                ViewBag.listJson = BasicTools.Object2JavaScriptJsonString("listJson", new { items = list });
			}
			return View();
		}

		public ActionResult LoginLogs(string userID)
		{
			using (var db = new DBEntities())
			{
				var user = (from u in db.users
						   where u.GUID == userID.ToLower()
						   select
							   new
							   {
								   u.GUID,
								   u.ShowName,
								   u.LoginName,
								   u.Email,
								   u.CreateDateTime,
								   LoginCount = u.user_loginlogs.Count
							   }).FirstOrDefault();

				var list = from l in db.user_loginlogs
						   where l.userID == userID.ToLower()
						   orderby l.LoginDateTime descending 
						   select
							   new
							   {
								   l.LoginDateTime
							   };

                ViewBag.userJson = BasicTools.Object2JavaScriptJsonString("userJson", user);
                ViewBag.listJson = BasicTools.Object2JavaScriptJsonString("listJson", new { items = list });
			}

			return View();
		}
	}
}

J.Web/Areas/HelpPage/Controllers/HelpController.cs
using System;
using System.Web.Http;
using System.Web.Mvc;
using J.Web.Areas.HelpPage.ModelDescriptions;
using J.Web.Areas.HelpPage.Models;

namespace J.Web.Areas.HelpPage.Controllers
{
    /// <summary>
    /// The controller that will handle requests for the help page.
    /// </summary>
    public class HelpController : Controller
    {
        private const string ErrorViewName = "Error";

        public HelpController()
            : this(GlobalConfiguration.Configuration)
        {
        }

        public HelpController(HttpConfiguration config)
        {
            Configuration = config;
        }

        public HttpConfiguration Configuration { get; private set; }

        public ActionResult Index()
        {
            ViewBag.DocumentationProvider = Configuration.Services.GetDocumentationProvider();
            return View(Configuration.Services.GetApiExplorer().ApiDescriptions);
        }

        public ActionResult Api(string apiId)
        {
            if (!String.IsNullOrEmpty(apiId))
            {
                HelpPageApiModel apiModel = Configuration.GetHelpPageApiModel(apiId);
                if (apiModel != null)
                {
                    return View(apiModel);
                }
            }

            return View(ErrorViewName);
        }

        public ActionResult ResourceModel(string modelName)
        {
            if (!String.IsNullOrEmpty(modelName))
            {
                ModelDescriptionGenerator modelDescriptionGenerator = Configuration.GetModelDescriptionGenerator();
                ModelDescription modelDescription;
                if (modelDescriptionGenerator.GeneratedModels.TryGetValue(modelName, out modelDescription))
                {
                    return View(modelDescription);
                }
            }

            return View(ErrorViewName);
        }
    }
}

J.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html class="no-js">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta http-equiv="Content-Language" content="zh-cn" />
    <meta name="viewport" content="width=device-width" />
    <meta name="description" content="The description of my page" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/all")
    @Scripts.Render("~/Scripts/all")
    @Scripts.Render("~/Scripts/jquery.uploadify")
    @Scripts.Render("~/Scripts/tinymce/js")
    @Scripts.Render("~/Scripts/tinymce/langs/zh_CN")


    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="~/Scripts/html5shiv.min.js"></script>
        <script src="~/Scripts/html5shiv-printshiv.min.js"></script>
        <script src="~/Scripts/respond.min.js"></script>
    <![endif]-->
    @RenderSection("head", required: false)
</head>
<body>
    <header class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("应用程序名称", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("主页", "Index", "Home", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("API", "Index", "Help", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Single", "Index", "Single", new { area = "" }, null)</li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    @if (Session[J.Logic.Basic.SessionConfig.CurrentUser] == null && System.Configuration.ConfigurationManager.AppSettings["LoginDialog"] == "true")
                    {
                        <li><a href="#" data-toggle="modal" data-target="#LoginDialog">登录</a></li>
                    }
                    @if (Session[J.Logic.Basic.SessionConfig.CurrentUser] == null && System.Configuration.ConfigurationManager.AppSettings["LoginDialog"] == "true" && System.Configuration.ConfigurationManager.AppSettings["EnableRegister"] == "true")
                    {
                        <li><a href="#" data-toggle="modal" data-target="#RegisterDialog">注册</a></li>
                    }
                    @if (Session[J.Logic.Basic.SessionConfig.CurrentUser] == null && System.Configuration.ConfigurationManager.AppSettings["LoginDialog"] != "true")
                    {
                        <li>@Html.ActionLink("登录", "Login", "User", new { area = "Common" }, null)</li>
                    }
                    @if (Session[J.Logic.Basic.SessionConfig.CurrentUser] == null && System.Configuration.ConfigurationManager.AppSettings["LoginDialog"] != "true" && System.Configuration.ConfigurationManager.AppSettings["EnableRegister"] == "true")
                    {
                        <li>@Html.ActionLink("注册", "Register", "User", new { area = "Common" }, null)</li>
                    }
                </ul>
            </div>
        </div>

    </header>

    <div class="container body-content">
        @RenderBody()
    </div>
    <footer class="container">
        <hr />
        <p>&copy; @DateTime.Now.Year - 我的 ASP.NET 应用程序</p>
    </footer>

    <div id="MessageBox" class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="alert alert-dismissable" id="MessageBox_alert">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <p id="MessageBox_message"></p>
                </div>
            </div>
        </div>
    </div>
   
    <script type="text/javascript">
        $('#MessageBox').on('hidden.bs.modal', function (e) {
            $("#MessageBox_alert").removeClass();
            $("#MessageBox_alert").addClass("alert alert-dismissable");
            $("#MessageBox_message").html("");
        })
    </script>


    @if (System.Configuration.ConfigurationManager.AppSettings["LoginDialog"] == "true")
    {
        @Html.Partial("~/Areas/Common/Views/User/_LoginDialog.cshtml")
    }
    @if (System.Configuration.ConfigurationManager.AppSettings["LoginDialog"] == "true" && System.Configuration.ConfigurationManager.AppSettings["EnableRegister"] == "true")
    {
        @Html.Partial("~/Areas/Common/Views/User/_RegisterDialog.cshtml")
    }

    @RenderSection("scripts", required: false)
</body>
</html>